### ISSUE TITLE
Outdated version on packagist

### ISSUE THREAD

**Issue by whisller** [michelsalib/BCCAutoMapperBundle#10]
Hey,
I've just noticed that version on packagist.org is referring to older hash `f026c1eac2fe4c1e899cd7fff4dfe7fd48268a32`. 

Is it possible to update it? :) It's little bit blocking upgrade to Symfony 2.7 on our projects.

**Comment by izquierdogalan** [comment]
meanwhile, you can refer to COMMIT until updated packagist
"bcc/auto-mapper-bundle": "dev-master#313df5e255cfc71ebbc9c01fb6defddf9c41d7d1",

**Comment by whisller** [comment]
@izquierdogalan thanks I know about this temporary solution. But would be good to fix this problem. 

You could set up hook that will notify packagist when repo is updated.

**Comment by whisller** [comment]
Ping @michelsalib

**Comment by michelsalib** [comment]
having a look

**Comment by michelsalib** [comment]
You now have version 1.1.0. If that's good you can close :)

**Comment by whisller** [comment]
Lovely, thanks @michelsalib !
