### ISSUE TITLE
Upgrade to Symfony3

### ISSUE THREAD

**Issue by mikeus-hanzlik** [michelsalib/BCCAutoMapperBundle#15]
Hello,

is it possible to update composer.json to allow dependencies on Symfony 3 packages?

**Comment by ektarum** [comment]
Hi,

Same question, need to pass to symfony 3 but not possible with BccAutoMapperBundle.

**Comment by rsaenen** [comment]
Hello,
I would be nice to be compatible with SF3 :)

**Comment by BenjaminPaap** [comment]
This project is now compatible with Symfony 3

**Comment by jaizquierdogalan** [comment]
I think we should do it compatible with sf3...

**Comment by BenjaminPaap** [comment]
Sorry, had a typo
